using System;
using System.Collections.Generic;

namespace PP.CodeTest
{
    /// <summary>
    /// This is just used to record the sequence of rule hits & the total amount generated by the system.
    /// It will enable to test if the rules are properly executed in the sequence.
    /// </summary>
    public class PromoEngineEventLogTrace
    {
        public List<CartItem> CartItems { get; }

        public double TotalAmount { get; set; }

        public Dictionary<int, Tuple<string, string>> Details { get; set; }
        private int _seqeuence = 1;

        public PromoEngineEventLogTrace(List<CartItem> items)
        {
            CartItems = items;
            Details = new Dictionary<int, Tuple<string, string>>();
        }

        public void HandlePromoDiscount(PromotionRule rule)
        {
            var promoPrice = Pricing.PromoPrice(rule.Code);
            TotalAmount += promoPrice;
            Details[_seqeuence] = new Tuple<string, string>($"{rule.Code}", $"Promo Price :{promoPrice} | Total Amount : {TotalAmount}");
            _seqeuence++;
        }

        public void CalculateTotal()
        {
            CartItems.ForEach(x =>
            {
                TotalAmount += Pricing.Price(x.Key) * x.Count;
            });
        }
    }
}